ft_aq:
  ros__parameters:
    # Sensor IP (eCAN)
    AFT80IP: "192.168.0.42"   # Robot side

    # Sensor CAN ID (10진수로 바꿔줌: 0x0b=11, 0x01=1)
    HandleID: 11        # 0x0b
    ContactID: 1        # 0x01

    # Sensor ACC
    HandleACC: false
    ContactACC: false

    # Sensor Sampling (s)
    Sensor_sampling: 0.002    # 500 Hz
    Publish_sampling: 0.008     # publish 주기 = 125Hz  (새로 추가)
  
    # Sensor Coordinate
    Handle_Sensor_Order: [2, 0, 1]
    Handle_Sensor_sign:  [1, 1, 1]

    Contact_Sensor_Order: [0, 1, 2]
    Contact_Sensor_sign:  [3, 3, 3]

    # Recording
    Data1_path: "/home/eunseop/nrs_ws/src/nrs_ft_aq2/measured/data1.txt"
    Data1_switch: 0

    # Print
    Print_switch: 1

    # Filter Switch
    Hmov_switch: false
    HLPF_switch: false
    HBSF_switch: false
    Cmov_switch: false
    CLPF_switch: false
    CBSF_switch: false
