% Jacobian
function KUKA_jaco = UR10_jacobian(th1,th2,th3,th4,th5,th6)
global a1 a2 a3 a4 a5 a6 a7 a8 a9 a10;
global d1 d2 d3 d4 d5 d6 d7 d8 d9 d10;

KUKA_jaco = [...
d6*(cos(th1)*cos(th5) + cos(th2 + th3 + th4)*sin(th1)*sin(th5)) + d4*cos(th1) - a3*cos(th2 + th3)*sin(th1) - a2*cos(th2)*sin(th1) - d5*sin(th2 + th3 + th4)*sin(th1),                          -cos(th1)*(a3*sin(th2 + th3) + a2*sin(th2) - d5*cos(th2 + th3 + th4) - d6*sin(th2 + th3 + th4)*sin(th5)),                           cos(th1)*(d5*cos(th2 + th3 + th4) - a3*sin(th2 + th3) + d6*sin(th2 + th3 + th4)*sin(th5)), cos(th1)*(d5*cos(th2 + th3 + th4) + d6*sin(th2 + th3 + th4)*sin(th5)), - d6*sin(th1)*sin(th5) - d6*cos(th2 + th3 + th4)*cos(th1)*cos(th5),                                                            0;
d6*(cos(th5)*sin(th1) - cos(th2 + th3 + th4)*cos(th1)*sin(th5)) + d4*sin(th1) + a3*cos(th2 + th3)*cos(th1) + a2*cos(th1)*cos(th2) + d5*sin(th2 + th3 + th4)*cos(th1),                          -sin(th1)*(a3*sin(th2 + th3) + a2*sin(th2) - d5*cos(th2 + th3 + th4) - d6*sin(th2 + th3 + th4)*sin(th5)),                           sin(th1)*(d5*cos(th2 + th3 + th4) - a3*sin(th2 + th3) + d6*sin(th2 + th3 + th4)*sin(th5)), sin(th1)*(d5*cos(th2 + th3 + th4) + d6*sin(th2 + th3 + th4)*sin(th5)),   d6*cos(th1)*sin(th5) - d6*cos(th2 + th3 + th4)*cos(th5)*sin(th1),                                                            0;
                                                                                                                                                                   0, a3*cos(th2 + th3) - (d6*sin(th2 + th3 + th4 + th5))/2 + a2*cos(th2) + (d6*sin(th2 + th3 + th4 - th5))/2 + d5*sin(th2 + th3 + th4), a3*cos(th2 + th3) - (d6*sin(th2 + th3 + th4 + th5))/2 + (d6*sin(th2 + th3 + th4 - th5))/2 + d5*sin(th2 + th3 + th4),            d5*sin(th2 + th3 + th4) - d6*cos(th2 + th3 + th4)*sin(th5),                                  -d6*sin(th2 + th3 + th4)*cos(th5),                                                            0;
                                                                                                                                                                   0,                                                                                                                          sin(th1),                                                                                                            sin(th1),                                                              sin(th1),                                      sin(th2 + th3 + th4)*cos(th1),   cos(th5)*sin(th1) - cos(th2 + th3 + th4)*cos(th1)*sin(th5);
                                                                                                                                                                   0,                                                                                                                         -cos(th1),                                                                                                           -cos(th1),                                                             -cos(th1),                                      sin(th2 + th3 + th4)*sin(th1), - cos(th1)*cos(th5) - cos(th2 + th3 + th4)*sin(th1)*sin(th5);
                                                                                                                                                                   1,                                                                                                                                 0,                                                                                                                   0,                                                                     0,                                              -cos(th2 + th3 + th4),                               -sin(th2 + th3 + th4)*sin(th5)];
end
