<?xml version="1.0"?>
<package format="3">
  <name>nrs_ft_aq2</name>
  <version>0.0.1</version>
  <description>ROS2 port of NRS_FT_AQ</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>MIT</license>

  <!-- build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- for nodes -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_srvs</depend>

  <!-- for msg generation -->
  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- 이 줄이 없어서 에러 난 거 -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export/>
</package>
