vr_demo_txt_recorder:
  ros__parameters:
    save_dir: "/home/eunseop/dev_ws/src/y2_ur10skku_control/Y2RobMotion/txtcmd"
    file_name: "cmd_continue9D.txt"

    start_force_th: 10.0
    end_force_th: 10.0
